exclude = [
    # these are private repositories, presumably any link to it are in internal documentation only.
    "^https://github.com/utnet-org/utility-private",

    # localhost is linked to refer to services supposed to be running on the host.
    "^http://localhost",

    # jsonrpc internal links
    "^file://.*/chain/jsonrpc/res/debug/",

    # used as placeholders for a template
    "^https://github.com/utnet-org/utility/pull/XXXX$",
]
