[package]
name = "unc-stdx"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "This crate contains polyfills which should really be in std, but currently aren't for one reason or another."
repository.workspace = true
license.workspace = true
publish = true

[lints]
workspace = true

[dependencies]
# Absolutely must not depend on any crates from framework workspace,
# and should have as few dependencies as possible otherwise.
