[package]
name = "unc-vm-types"
version.workspace = true
description = "unc VM Common Types"
categories = ["wasm", "data-structures"]
keywords = ["wasm", "webassembly", "types"]
authors = ["Wasmer Engineering Team <engineering@wasmer.io>", "Hello Inc <hello@unc.com>"]
repository.workspace = true
license = "GPL-2.0-or-later"
readme = "README.md"
edition = "2021"
publish = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
indexmap.workspace = true
num-traits.workspace = true
rkyv.workspace = true

[dev-dependencies]
bolero.workspace = true

[[test]]
name = "partial-sum-map"
