[package]
name = "mock-node"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
actix-rt.workspace = true
actix.workspace = true
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
pin-project.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true

unc-actix-test-utils.workspace = true
unc-async.workspace = true
unc-chain.workspace = true
unc-chain-configs.workspace = true
unc-client.workspace = true
unc-crypto.workspace = true
unc-chunks.workspace = true
unc-epoch-manager.workspace = true
unc-jsonrpc.workspace = true
unc-jsonrpc-client.workspace = true
unc-network.workspace = true
unc-store.workspace = true
unc-o11y.workspace = true
unc-telemetry.workspace = true
unc-performance-metrics.workspace = true
unc-primitives.workspace = true
framework.workspace = true

[[bin]]
name = "mock-node"

[features]
test_features = ["framework/test_features"]
