[book]
language = "en"
multilingual = false
src = "."
title = "Guide to Nearcore Development"

[build]
# Let's re-use the existing target dir for all build artifacts.
build-dir = "../target/book"

[output.html]
git-repository-url = "https://github.com/utnet-org/utility/tree/master/docs"
edit-url-template = "https://github.com/utnet-org/utility/edit/master/docs/{path}"
