[package]
name = "store-validator"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
yansi.workspace = true

unc-epoch-manager.workspace = true
unc-chain-configs.workspace = true
unc-primitives.workspace = true
unc-store.workspace = true
unc-o11y.workspace = true
unc-chain.workspace = true
framework.workspace = true

[dev-dependencies]
testlib.workspace = true
serde_json.workspace = true
unc-client.workspace = true
