[package]
name = "style-tests"
version = "0.0.0"
edition = "2021"
publish = false
description = "An entry point for miscelaneous (stylistic) workspace-wide tests"
authors = ["Hello Inc <hello@unc.com>"]

[lints]
workspace = true

[dependencies]
